name: Anne K. Johnson
description: Personal site of Anne K. Johnson
url: http://annekjohnson.com
markdown: redcarpet
highlighter: pygments
encoding: utf-8
permalink: /blog/:year/:month/:title/index.html
source: source/
paginate: 5
paginate_path: "/blog/page/:num"
gems: [jekyll-paginate]

collections:
  art:
    output: true
    permalink: /art/:path/
  code:
    output: true
    permalink: /code/:path/
