title: Anne K. Johnson
description: Personal site of Anne K. Johnson
url: https://annekjohnson.com
markdown: kramdown
encoding: utf-8
permalink: /blog/:year/:month/:title/index.html
source: source/
paginate: 5
paginate_path: "/blog/page/:num"
plugins:
  - jekyll-feed
feed:
  path: blog/feed.xml
  tags:
    path: blog/feed.
    only:
      - clojure
      - clojurescript

collections:
  art:
    output: true
    permalink: /art/:path/
  code:
    output: true
    permalink: /code/:path/
